import 'dart:convert';
import 'dart:io';
import 'package:http/http.dart' as http;
import '../config/constants.dart';

class MediaService {
  static const String _baseUrl = Constants.apiUrl;

  /// Uploads a file directly to Cloudflare R2 using a pre-signed URL generated by our backend.
  /// This prevents the file from passing through our server, saving bandwidth and processing power.
  static Future<String?> uploadMediaDirectlyToR2(File file) async {
    try {
      final fileName = file.path.split('/').last;
      
      // Determine content type (simple check for example, can be improved)
      String contentType = 'application/octet-stream';
      if (fileName.toLowerCase().endsWith('.jpg') || fileName.toLowerCase().endsWith('.jpeg')) {
        contentType = 'image/jpeg';
      } else if (fileName.toLowerCase().endsWith('.png')) {
        contentType = 'image/png';
      } else if (fileName.toLowerCase().endsWith('.mp4')) {
        contentType = 'video/mp4';
      }

      // 1. Get the pre-signed URL from our backend
      final urlResponse = await http.get(
        Uri.parse('$_baseUrl/generate-upload-url?fileName=$fileName&contentType=$contentType'),
      );

      if (urlResponse.statusCode != 200) {
        print('Error generating upload URL: ${urlResponse.body}');
        return null;
      }

      final urlData = jsonDecode(urlResponse.body);
      final String signedUrl = urlData['signedUrl'];
      final String publicUrl = urlData['publicUrl'];

      // 2. Upload the file directly to Cloudflare R2 using the signed URL
      final fileBytes = await file.readAsBytes();
      final uploadResponse = await http.put(
        Uri.parse(signedUrl),
        headers: {
          'Content-Type': contentType,
        },
        body: fileBytes,
      );

      if (uploadResponse.statusCode == 200) {
        // Upload successful! Return the public URL to be saved in the database
        print('File successfully uploaded to R2: $publicUrl');
        return publicUrl;
      } else {
        print('Failed to upload file to R2: ${uploadResponse.statusCode} - ${uploadResponse.body}');
        return null;
      }
    } catch (e) {
      print('Exception during direct R2 upload: $e');
      return null;
    }
  }

  /// Creates a moment in the database after the media has been uploaded directly to R2.
  static Future<bool> createMoment(String userId, String mediaUrl, String? caption) async {
    try {
      final response = await http.post(
        Uri.parse('$_baseUrl/moments'),
        headers: {'Content-Type': 'application/json'},
        body: jsonEncode({
          'userId': userId,
          'mediaUrl': mediaUrl,
          'caption': caption,
        }),
      );

      return response.statusCode == 200;
    } catch (e) {
      print('Exception creating moment: $e');
      return false;
    }
  }
}
